### ISSUE TITLE
License to use?

### ISSUE THREAD

**Issue by avijit-thawani** [mustafadalga/youtube-ui-clone#1]
Hi @mustafadalga thank you for this great repository!

We (students at Univ of Southern California) wanted to extend your framework for a hobby project (with due credits of course) but could not find a license - which by default translates to the most restrictive one.

Could you please add a license so we can proceed with extending your project officially? Here's more info on Github licenses: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by mustafadalga** [comment]
Hi @avi-jit , 
Which project do you mean ?

**Comment by avijit-thawani** [comment]
We're trying to build a recommendation engine for fun, and it would be nice to have it look like youtube, for which your youtube-ui-clone repo is a great starting point!

**Comment by mustafadalga** [comment]
@avi-jit  Okay. I added. Good luck!
